name: 卡牌库:皇室战争
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - static/img/icons/
    - static/img/loading/
    - static/img/army/three_musketeers.png
    - static/img/army/chr_golem.png
    - static/img/army/royal_recruits.png
    - static/img/army/pekka.png
    - static/img/army/lava_hound.png
    - static/img/army/mega_knight.png
    - static/img/army/royal_giant.png
    - static/img/army/angry_barbarian.png
    - static/img/army/giant_skeleton.png
    - static/img/army/goblin_giant.png
    - static/img/army/zapMachine.png
    - static/img/army/barbarians.png
    - static/img/army/minion_horde.png
    - static/img/army/rascals.png
    - static/img/army/chr_balloon.png
    - static/img/army/chr_witch.png
    - static/img/army/prince.png
    - static/img/army/bowler.png
    - static/img/army/executioner.png
    - static/img/army/cannon_cart.png
    - static/img/army/electro_dragon.png
    - static/img/army/ram_rider.png
    - static/img/army/giant.png
    - static/img/army/wizard.png
    - static/img/army/royal_hog.png
    - static/img/army/baby_dragon.png
    - static/img/army/dark_prince.png
    - static/img/army/hunter.png
    - static/img/army/rage_barbarian.png
    - static/img/army/inferno_dragon.png
    - static/img/army/electro_wizard.png
    - static/img/army/dark_witch.png
    - static/img/army/magic_archer.png
    - static/img/army/valkyrie.png
    - static/img/army/musketeer.png
    - static/img/army/mini_pekka.png
    - static/img/army/hog_rider.png
    - static/img/army/battle_ram.png
    - static/img/army/flying_machine.png
    - static/img/army/zappies.png
    - static/img/army/knight.png
    - static/img/army/archers.png
    - static/img/army/minion.png
    - static/img/army/bomber.png
    - static/img/army/goblin_gang.png
    - static/img/army/skeleton_balloon.png
    - static/img/army/skeleton_horde.png
    - static/img/army/skeleton_warriors.png
    - static/img/army/ice_wizard.png
    - static/img/army/princess.png
    - static/img/army/miner.png
    - static/img/army/bandit.png
    - static/img/army/ghost.png
    - static/img/army/mega_minion.png
    - static/img/army/blowdart_goblin.png
    - static/img/army/goblins.png
    - static/img/army/goblin_archer.png
    - static/img/army/fire_spirits.png
    - static/img/army/bats.png
    - static/img/army/ice_golem.png
    - static/img/army/skeletons.png
    - static/img/army/snow_spirits.png
    - static/img/building/barbarian_hut.png
    - static/img/building/building_xbow.png
    - static/img/building/building_elixir_collector.png
    - static/img/building/fire_furnace.png
    - static/img/building/building_inferno.png
    - static/img/building/building_mortar.png
    - static/img/building/building_tesla.png
    - static/img/building/bomb_tower.png
    - static/img/building/firespirit_hut.png
    - static/img/building/chaos_cannon.png
    - static/img/building/tombstone.png
    - static/img/spell/lightning.png
    - static/img/spell/rocket.png
    - static/img/spell/graveyard.png
    - static/img/spell/freeze.png
    - static/img/spell/poison.png
    - static/img/spell/fire_fireball.png
    - static/img/spell/order_volley.png
    - static/img/spell/goblin_barrel.png
    - static/img/spell/tornado.png
    - static/img/spell/copy.png
    - static/img/spell/heal.png
    - static/img/spell/zap.png
    - static/img/spell/snowball.png
    - static/img/spell/rage.png
    - static/img/spell/barb_barrel.png
    - static/img/spell/the_log.png
    - static/img/spell/mirror.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
